### ISSUE TITLE
There's no "starting guide"

### ISSUE THREAD

**Issue by q2dg** [malwaredllc/byob#113]
I've run server and client but I've not known what to do afterwards.
Thanks

**Comment by FraggleR0ck** [comment]
get the cli command wrong it crashes the server. Some basic cli commands other than help with no idea on what is needed to be inputted. I like where you are going with this project though.

**Comment by Emilarity** [comment]
> get the cli command wrong it crashes the server. Some basic cli commands other than help with no idea on what is needed to be inputted. I like where you are going with this project though.

If it helps, I was having this crashing problem too, then I realized my client (built using the --freeze option) was bundled with python3 instead of python2. After fixing that, getting the command wrong showed a usage string instead of crashing. :yum: 

For the most part I think this program is self-explanatory when you get everything running smoothly, and it's a good starting point for something bigger. It expects you to read the code—it's an educational project after all—and I think that's fine.

**Comment by malwaredllc** [comment]
@q2dg @FraggleR0ck @Emilarity Many bugs have been fixed and improvements have been made (including support for Python3) since this issue was submitted.
I would suggest doing a fresh install and trying again - it should now be a much smoother experience.
However, I am definitely going to put together a "getting started guide" with some screenshots and examples - thanks for the input!
