### ISSUE TITLE
Clients not connect to server

### ISSUE THREAD

**Issue by yamortsa** [malwaredllc/byob#151]
I didn't see any connection from the client to the server. How can I fix this issue?

![VirtualBox_Alice_24_09_2019_01_00_54](https://user-images.githubusercontent.com/28704143/65450370-24afa780-de67-11e9-9570-90b17b5eb382.png)

**Comment by rotzbouf** [comment]
Can be solved by running the client. Compiling it, is not enough.

**Comment by yamortsa** [comment]
lol, I already ran it

**Comment by rotzbouf** [comment]
According your screenshots, you only compiled it, but did not executed the compiled client. 
Please provide logs about the error or any detail which helps troubleshooting.

**Comment by yamortsa** [comment]
yep, that is the point I want to mention, I didn't see any option to troubleshoot when I execute the client.
I mean It like --debug option or something like that

**Comment by rotzbouf** [comment]
what is the exact command you use to run it?
Do you run server and client on same host? Probably yes.
What OS do you use for client/server? Likely Win.
Did you try running the server on localhost instead of you LAN ip? Probably not.
Since runng bothe (client and server) on same host, try also connecting client to localhost.
When running the server, make sure you port is open and listening (nmap).
