### ISSUE TITLE
Client can’t connect 

### ISSUE THREAD

**Issue by Deb-kal** [malwaredllc/byob#154]
Hi,
I’m on Kali Linux and clients can’t connect to server. Tested locally and over WAN.

After installing all dependencies, running the server with python 3.7 : `python3.7 server.py --host 192.168.1.1 --port 8080`

Launching Windows 10 x64 on Virtualbox, install all dependencies and build client (with python3.7) `python client.py MyPublicIp 8080`
After this I execute the output file and nothing appears. Client don’t connect to server. 
For WAN I have already portforwarded correctly my router. 

I saw something bizarre : 

When I build using 8080 the server seems uploading things on port 8081. After sawing this I have tried to use port 8079 when building and guess what ? The command prompt stay open like there is something working but I didn’t get the Client on the server with the [+].  And when I stop the client by quitting the command prompt I got something on the server that say `Connection failed : 80.108.X.X` ( The IP address of my virtual machine executing the client ) 

I really don’t understand what’s happening.

**Comment by rotzbouf** [comment]
Might be related to Kali firewall settings. Make sure 8080 is open and listening on server side.
Make sure your client is using same port for connection as server is listening to.
Surely a network setup issue. Not related to the software itself.

**Comment by rotzbouf** [comment]
The connection listening to port 8081 etc are services started from the server when launching server.py used by clients to import new modules etc. Try pointing your browser to this port and see what happens.

**Comment by mjlally** [comment]
I can't connect if I run the client and server with python 3.7. It works well with python 2.7 though.

As for the ports, if you read through the code, apart from the base port you specify, or the default port if you do not specify, 3 other ports are used (at least). So if using 8080, it will also use 8081, 8082, 8083. I think the base port is the direct communication with the server, base +1 and base +2 are http used for the client to download code etc for use. Base +3 might be for the database connection, not checked yet though, but will be easy to see in the code.

I had some issues caused by thew fact some of the http.server processes were still running after I exited and tried using port numbers that overlapped those used previously, but using kill -s 9 or a different base port fixes that.

I think your issue is due to using python 3.7.

**Comment by fu050409** [comment]
I got a similar error.
I am Windows, on local machine the same as you. I am able to connect but failed to start shell.

**Comment by malwaredllc** [comment]
@mjlally @fu050409 @rotzbouf I have pushed a lot of bug fixes and improvements recently (including support for Python3), so I would recommend doing a fresh install and trying again. Let me know if you have any issues.
