### ISSUE TITLE
--exe and --app loop

### ISSUE THREAD

**Issue by SecT0uch** [malwaredllc/byob#21]
When executing client.py from Linux (Debian), I've got an infinite loop at compilation ("Dropper" step).
When I cancel the command, it says `saved to file: /home/jordan/byob/byob/dist/byob_xxx)`.
But it seems to be a linux executable : 
`$ file dist/byob_qH8 
dist/byob_qH8: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7670e166c8dd74a98464b6711462f8a4fc391b75, stripped`

**Comment by colental** [comment]
Ok thanks for letting me know - I will try to replicate the issue and get back to your shortly.

**Comment by mshirley** [comment]
this is happening because the output from the PyInstaller module is going to stderror instead of stdout.  the ```while True``` loop never completes but the package is compiled by the process in the background.

https://github.com/colental/byob/blob/c719219b74245032f7f492974c1b88a40f46d3a6/byob/core/generators.py#L191

```line = process.stderr.readline().rstrip()``` fixes the issue for me but i'm not sure if that's the correct solution for multiple platforms.  it might be better to redirect stderr to stdout when creating the process?

**Comment by KALRONG** [comment]
The above fixed my loop issue too, but I dont get the exe file, just a a linux executable like its said in the first comment, here is the complete trace:

`260 INFO: Python: 2.7.13
261 INFO: Platform: Linux-4.9.0-7-amd64-x86_64-with-debian-9.5
263 INFO: UPX is not available.                                                                                                                                                                                                             \632 INFO: Extending PYTHONPATH with paths
['/home/kalrong/byob', '/home/kalrong/byob/byob']
632 INFO: Will encrypt Python bytecode with key: kBZeuZ;2h2GLuMVy
632 INFO: Adding dependencies on pyi_crypto.py module
632 INFO: checking Analysis
632 INFO: Building Analysis because out00-Analysis.toc is non existent
632 INFO: Initializing module dependency graph...
634 INFO: Initializing module graph hooks...
637 INFO: Analyzing hidden import 'base64'                                                                                                                                                                                                  |2071 INFO: Analyzing hidden import 'zlib'
2071 INFO: Analyzing hidden import 'urllib'                                                                                                                                                                                                 /2630 INFO: Analyzing hidden import 'Crypto.Cipher.AES'                                                                                                                                                                                      |3776 INFO: Processing pre-find module path hook   distutils                                                                                                                                                                                 -4844 INFO: Processing pre-safe import module hook   _xmlplus                                                                                                                                                                                /6620 INFO: Analyzing hidden import 'json'
6723 INFO: Analyzing hidden import 'numpy'                                                                                                                                                                                                  |13382 INFO: Analyzing hidden import 'uuid'                                                                                                                                                                                                  \13403 INFO: Analyzing hidden import 'logging.handlers'
13466 INFO: Analyzing hidden import 'colorama'
13567 INFO: Analyzing hidden import 'requests'                                                                                                                                                                                              /13920 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves                                                                                                                                                             -16795 INFO: Processing pre-safe import module hook   six.moves                                                                                                                                                                              /17838 INFO: running Analysis out00-Analysis.toc
17858 INFO: Caching module hooks...
17861 INFO: Analyzing /home/kalrong/byob/byob/test.py
17872 INFO: Loading module hooks...
17872 INFO: Loading module hook "hook-distutils.py"...
17873 INFO: Loading module hook "hook-sysconfig.py"...
17874 INFO: Loading module hook "hook-xml.py"...                                                                                                                                                                                            |17996 INFO: Loading module hook "hook-pycparser.py"...                                                                                                                                                                                     \18230 INFO: Loading module hook "hook-httplib.py"...
18230 INFO: Loading module hook "hook-pydoc.py"...
18232 INFO: Excluding import 'Tkinter'
18233 INFO:   Removing import of Tkinter from module pydoc
18233 INFO: Loading module hook "hook-encodings.py"...                                                                                                                                                                                      /18651 INFO: Loading module hook "hook-_tkinter.py"...
18707 INFO: checking Tree
18707 INFO: Building Tree because out00-Tree.toc is non existent
18707 INFO: Building Tree out00-Tree.toc
18740 INFO: checking Tree
18740 INFO: Building Tree because out01-Tree.toc is non existent
18740 INFO: Building Tree out01-Tree.toc
18753 INFO: Loading module hook "hook-pkg_resources.py"...                                                                                                                                                                                  -19203 INFO: Processing pre-safe import module hook   win32com                                                                                                                                                                               /19452 INFO: Loading module hook "hook-requests.py"...
19453 INFO: Loading module hook "hook-certifi.py"...
19453 INFO: Loading module hook "hook-setuptools.py"...
19490 INFO: Loading module hook "hook-cryptography.py"...                                                                                                                                                                                   |19637 INFO: Loading module hook "hook-numpy.core.py"...
19723 INFO: Looking for ctypes DLLs                                                                                                                                                                                                         \19853 INFO: Analyzing run-time hooks ...
19862 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
19867 INFO: Including run-time hook 'pyi_rth_pkgres.py'
19868 INFO: Including run-time hook 'pyi_rth__tkinter.py'
19883 INFO: Looking for dynamic libraries                                                                                                                                                                                                   \20608 INFO: Looking for eggs
20608 INFO: Python library not in binary dependencies. Doing additional searching...
20625 INFO: Using Python library /lib/x86_64-linux-gnu/libpython2.7.so.1.0
20634 INFO: Warnings written to /home/kalrong/byob/byob/build/test/warntest.txt
20707 INFO: Graph cross-reference written to /home/kalrong/byob/byob/build/test/xref-test.html                                                                                                                                                  -20906 INFO: checking PYZ
20906 INFO: Building PYZ because out00-PYZ.toc is non existent
20906 INFO: Building PYZ (ZlibArchive) /home/kalrong/byob/byob/build/test/out00-PYZ.pyz                                                                                                                                                         \22350 INFO: Building PYZ (ZlibArchive) /home/kalrong/byob/byob/build/test/out00-PYZ.pyz completed successfully.                                                                                                                                 -22488 INFO: checking PKG
22488 INFO: Building PKG because out00-PKG.toc is non existent
22488 INFO: Building PKG (CArchive) out00-PKG.pkg                                                                                                                                                                                           |36428 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
36487 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run_d
36487 INFO: checking EXE
36487 INFO: Building EXE because out00-EXE.toc is non existent
36487 INFO: Building EXE from out00-EXE.toc
36487 INFO: Appending archive to ELF section in EXE /home/kalrong/byob/byob/dist/test
36552 INFO: Building EXE from out00-EXE.toc completed successfully.
(saved to file: /home/kalrong/byob/byob/dist/test)
`

**Comment by malwaredllc** [comment]
PyInstaller compiles standalone binaries in the executable format of the platform of the host system it is running on. 

For the purposes of this project, the most important are:

- PE/Portable Executable (Windows)
- ELF/Executable and Linkable Format (Linux)
- APP/Bundled Application (macOS)

This is a limitation of PyInstaller which I personally do not know how to circumvent - if anyone has any ideas for how to cross-compile binaries in different executable formats irregardless of the host platform, please let me know.

**Comment by VanillaScent** [comment]
A fix for this should be as stated above, as it only compiles to the format of the current operating system, so making a virtual machine with windows and then setting it up for this git, you should then be able to built the .exe

**Comment by malwaredllc** [comment]
This issue should now be fixed - try it out and let me know.

**Comment by SecT0uch** [comment]
Regarding the loop, the problem is fixed, however I still get a Linux binary with the --exe option.
