### ISSUE TITLE
Errors running the Payload in victims machine etc.

### ISSUE THREAD

**Issue by MiChaelinzo** [malwaredllc/byob#291]
<img width="329" alt="byob1" src="https://user-images.githubusercontent.com/68110223/95102018-8756a700-073b-11eb-9c87-591ad369ea60.PNG">
<img width="337" alt="byob2" src="https://user-images.githubusercontent.com/68110223/95102023-89206a80-073b-11eb-95a1-00311f9df0b2.PNG">

**Comment by MiChaelinzo** [comment]
victims machine is running latest Python 3.8.6

**Comment by Dipraj2** [comment]
same problem here :")

**Comment by Dipraj2** [comment]
help plz

**Comment by ricko2991** [comment]
If you use byob via command line, use python2 to create. And also use windows to create payload

If you use web-gui, use python3 to create.

**Comment by MiChaelinzo** [comment]
> If you use byob via command line, use python2 to create. And also use windows to create payload
> 
> If you use web-gui, use python3 to create.
> 
> **In essence, the attacker and the target must both use the same os**

I can create payloads within cli using py3 etc. the payload i created is py3 within web-gui
and what do you mean by " In essence, the attacker and the target must both use the same os " do you mean a winx32 payload created in linux won't work to target windows os? or do you mean winx32 payload works for windows and nixamd64 or nixi386 works for linux etc? which i think anyone knows

**Comment by ricko2991** [comment]
What I mean here byob (cli). in web-gui it will still work if you use it for windows, because it compiles it using wine in the nix-win32 image. Can you see the code contents of the python payload that you have created. There may be some kind of encoder we can't read. You just need to decode the script and see what problems it has. Cause I don't usually just use the compiled payload to the executable automatically, it will make it difficult for us to see where the mistake is. Once you find the error, you can compile it to the executable manually.

**Comment by Dipraj2** [comment]
Still not working
Same errors

**Comment by malwaredllc** [comment]
This error message indicates you haven't set up your network correctly (i.e. you need to do some port forwarding etc). For help with this, please join the Discord support server.
