### ISSUE TITLE
problem with payload generator with byob

### ISSUE THREAD

**Issue by Fearinmyhead** [malwaredllc/byob#303]
so as everyone im facing ungenreted files from payload i read that there is a problem with the startup.sh and someone try to fix it but i didnt see any publish so i dig a little bit and i cross by a mini solution that i can genrete python.py with payload and manually with pyinstaller convert it from py to exe so after 4 hours of how do i make this and facing all the eroor accourd i finally made one but now im just strated programmng idk how i "move my bot exe file to the control panel and see it as active bot its direct folder is in the downloads section i need to move it to webgui somewhere or something? 
p.s on extracted file on webgui i didnt see any of the exe file i made

**Comment by ricko2991** [comment]
For now make payload just for linux on web-gui. There is a problem if you make executable payload for windows. Maybe because it hasn't been updated by the owner for a long time. But if you run byob/not web-gui on windows it will make the payload work, and you can run it as an executable. You can make improve for the code or still waiting for improvements from the main team. the update will come soon.

**Comment by ricko2991** [comment]
https://youtu.be/TBSh_w0I-z8
