### ISSUE TITLE
ImportError: no module named colorama

### ISSUE THREAD

**Issue by HyperProxy** [malwaredllc/byob#313]
I'm on macOS Catalina and when I run server.py, it comes back with the error of: "ImportError: no module named colorama". I don't know if that is a function of being on macOS, but let me know! Thanks, lucas

**Comment by YoBot389** [comment]
I also had the same problem but it was as simple as that.

**Download Link For Colorama**: https://pypi.org/project/colorama/#files

* This is a python requirement so you will need to search manually everytime every requirement to install ( the amount of errors you get )

That might look really complicated but hit me up so I can tell you more detailed help because im in a hurry right now.

Sincerely, 
Alex

**Comment by Bobert2732** [comment]
Hi, I have the same problem... when I try to start client.py it give me the same error, the problem is that I already have colorama downloaded and updated and I am using Kali Linux, can you help me please?
