### ISSUE TITLE
can't get a connection

### ISSUE THREAD

**Issue by user568989** [malwaredllc/byob#35]
i run the client.py with the host and port as i want and in the "BYOB" u get  a python file i run the file in IDLE and run it and i get this error:

![screenshot 2](https://user-images.githubusercontent.com/42979542/45231328-542f5880-b2d4-11e8-9068-a1a3202edd38.png)
![screenshot 4](https://user-images.githubusercontent.com/42979542/45231329-54c7ef00-b2d4-11e8-81de-9a98c1813af7.png)

any ideas?

the error is in picture one

**Comment by malwaredllc** [comment]
What specific command did you use to generate the client? And what specific command are you using to run the server?

**Comment by user568989** [comment]
run te client :
from CMD
python client.py x.x.x.x 1337

in kali linux (attacker, server)

server.py --host x.x.x.x --port 1337

**Comment by malwaredllc** [comment]
The client aborts execution if a virtual machine is detected, in order to prevent run-time analysis. If you want to run the client on a virtual machine, you need to use the `--debug` option when launching it (ex. `python byob_w7G.py --debug`). When it prompts "Virtual machine detected. Abort? (y/n)", enter "n" and the client execution will continue.

**Comment by user568989** [comment]
hey can u send me a video how to do it step by step or tell me by
1.***
2.****
3.***
 have a look at this i tried what u told me and it did not work
