### ISSUE TITLE
Failed to execute script pyi_rth_pkres

### ISSUE THREAD

**Issue by MathesAlla** [malwaredllc/byob#356]
Hello, i generated a Windows client but can`t run it im getting the error "Failed to execute script pyi_rth_pkres"
hope you can help me.

**Comment by DrunkenMoose** [comment]
I'm also getting this error on my Windows 10 device. I made the .exe through the web.ui (127.0.0.1:5000) but get that error. And the .py isn't working on my raspberry pi. I also tried the client.py script through the console, but then I get a 
"Appending archive to ELF section in EXE /home/drunkenmoose/byob-master/byob/dist/vrb" vrb file? I tried to make an EXE
file, but Windows doesn't get it. (I now understand that because I run this command in linux then it should make a linux payload, but this file is just nothing or something?)

**Comment by UnturnedZoggs** [comment]
i am also getting this
