### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ardavanhashemzadeh** [malwaredllc/byob#36]
Hello,
In attempting to design a solution to help me manage the fleet of machines I'm responsible for I realized that my plans closely resemble a botnet, so I searched and landed on your project. Would you recommend your project as a base to build a management solution (for mainly windows clients), or do you know of any better suited open source projects? I apologize for spamming the bug tracker, but didn't know how else to reach out.
Thanks,
~ardy

**Comment by ialhashim** [comment]
I was planning to use it for a similar task, I already started a Python 3 fork and made some functionality work. But my impression so far is that the project is still under heavy development. I plan to come back to it once things stabilize some more.

**Comment by VanillaScent** [comment]
It seems pretty usable, aside the occasional bug

**Comment by intrct** [comment]
I would highly recommend NOT using this for remote administration of your systems; not because the developers of this have bad intentions but because this system is meant to be a means of accessing systems (with little in the way of source validation)

Understand that most remote administration systems you use, you would want to have some form of authentication or authorization for the things you are having done. Also, you would want it to be lightweight and capable of performing a plethora of tasks in a large number of environments (and more importantly TESTED in a large number of environments).

If you need a remote administration option that has all of these concepts included in its design, I HIGHLY suggest moving your attention to Ansible or Salt (salt-ssh) which are both free and open source.
