### ISSUE TITLE
Missing manual

### ISSUE THREAD

**Issue by ServerMonkey** [malwaredllc/byob#368]
How to use this program without the web-interface?

I connect to session 0 with:
shell 0
Works fine!
I'm in: [ 0 @ /home/user/Downloads ]

I try: ransom 0
nothing happens on the client

I try: screenshot
Get error: screenshot error: 'module' object has no attribute 'run'

I try: escalate
Privilege escalation not yet available on 'linux2'

Nothing seems to work.
How do you actually use this program?
I read every manual I could find there is only this:
https://github.com/malwaredllc/byob/wiki/Server-Commands
https://byob.dev/docs has nothing of value.
All other tutorials i find online do not show anything about how to interact with the shell or how to automate.

If there is a proper manual or a tutorial, please show me.
What am I missing here?

**Comment by malwaredllc** [comment]
You can use the 'help' command to see the usage information and correct syntax for the various commands and post-exploitation modules.

This error "screenshot error: 'module' object has no attribute 'run'" indicates the payload is probably failing to remotely import the screenshot module from your C2 server, likely because of how your network is set up. Make sure ports 1337-1340 are listening externally and any necessary port-forwarding has been done.

As a test to check if your network is configured properly, when your C2 server is running, from that same machine you can open the browser and go to http://0.0.0.0:1339 you should see a list of files/directories.
