### ISSUE TITLE
"Unable to find image 'win-x32:latest' locally" when trying to create win payload

### ISSUE THREAD

**Issue by gsqsimjaa** [malwaredllc/byob#370]
So I was trying to create a Executable Windows x32 payload. When trying to create this, this comes out:
```
/usr/bin/docker
(343 bytes written to output/simjaa/src/byob_win_x32_tA8.py)
	Compiling executable...

b"Unable to find image 'win-x32:latest' locally"
b"docker: Error response from daemon: pull access denied for win-x32, repository does not exist or may require 'docker login'."
b"See 'docker run --help'."

```
I am using byob on a raspberry Pi. 

Edit: When trying to create executable linux file, this comes up: 
`/usr/bin/docker
(343 bytes written to output/simjaa/src/byob_nix_amd64_c8h.py)
	Compiling executable...

b"Unable to find image 'nix-amd64:latest' locally"
b"docker: Error response from daemon: pull access denied for nix-amd64, repository does not exist or may require 'docker login'."
b"See 'docker run --help'."`

**Comment by Tiny-Lamma** [comment]
same error on Ubuntu 20.04.1 LTS

**Comment by uyeet** [comment]
try reinstalling using git clone or reinstall requirements. sudo ./startup.sh

**Comment by malwaredllc** [comment]
From Discord FAQ:

"The first thing you should do is update to the latest version of byob if you are not on it already. Next you should reboot your system if it hasn’t rebooted since byob was installed. Finally, run the commands “sudo usermod -aG docker (username)” and “sudo chmod 666 /var/run/docker.sock” then reboot your system. If this doesn’t work, uninstall docker and run startup.sh again (it will reinstall docker for you) then reboot your system (or answer yes to the prompt at the end of the script)."
