### ISSUE TITLE
Termux version of byob

### ISSUE THREAD

**Issue by Peanutzy** [malwaredllc/byob#432]
Please make a termux version of byob😭

**Comment by garsh1** [comment]
What even is Termux?

**Comment by malwaredllc** [comment]
If you want to create a fork, add this feature, and create a PR I will be happy to review it

**Comment by sinaj2889** [comment]
> What even is Termux?

A terminal app for android phones it works the same as linux

**Comment by CSaV720** [comment]
Everything is correct on termux apart from python metadata in the "setup.py" in the "/home/hali/byob/byob" directory to do installs from requirements.txt (im on a python venv also it returns subprocess error).

no metadata can be formed in python project wheel.

i dont think termux will have a working version of byob unless you run it in a gui interface because you will need to reconfigure with python idle . You could use nano but you will still be met with sub processing error on metadata because BYOB has win32 architecture and it doesn't support recent python 3.12 environment. You will have to use python2
