### ISSUE TITLE
All port are open but don't work payload

### ISSUE THREAD

**Issue by Ugroon** [malwaredllc/byob#483]
![portsopen1](https://user-images.githubusercontent.com/77273551/124322007-5cdd3180-db87-11eb-9e41-764c85942fab.png)
![portareopen2](https://user-images.githubusercontent.com/77273551/124322018-62d31280-db87-11eb-8b83-bd107c1a4707.png)
![payload](https://user-images.githubusercontent.com/77273551/124321995-55b62380-db87-11eb-87ad-d7bcbb97d2bb.png)

**Comment by smrinalsingh** [comment]
So, I did some analysis and seems like the generated payload is trying to connect to port 1338 but by default the server runs on 1337. I've been scanning through the files now but can't seem to pin point to the location this is happening at.

![image](https://user-images.githubusercontent.com/3834741/124802567-bd98af80-df75-11eb-88aa-93fe2f36dc55.png)

I replaced the compressed / encoded part of the dropper to plain string with port 1337 mentioned and this time the script did not get terminated due to connection error - I still don't see the machine turn up on the dashboard. Checked a little more on the connection front using WireShark and seems like are these 'Keep Alive' packets floating around from time to time.

![image](https://user-images.githubusercontent.com/3834741/124803172-68a96900-df76-11eb-9dd6-939084663b6c.png)

Any help would be appreciated.

**Comment by garsh1** [comment]
The payloads use ports 1337, 1338, and 1339 for connections. Please join the discord for support.

**Comment by debian-user-france1** [comment]
No why should he join Discord when you can report 'bugs' here. Also got supported here!

**Comment by debian-user-france1** [comment]
> ![portsopen1](https://user-images.githubusercontent.com/77273551/124322007-5cdd3180-db87-11eb-9e41-764c85942fab.png)
> ![portareopen2](https://user-images.githubusercontent.com/77273551/124322018-62d31280-db87-11eb-8b83-bd107c1a4707.png)
> ![payload](https://user-images.githubusercontent.com/77273551/124321995-55b62380-db87-11eb-87ad-d7bcbb97d2bb.png)

This is mostly caused by a firewall. For ubuntu execute this: sudo service ufw stop. To disable it (not starting on restart) execute: sudo systemctl ufw disable
