### ISSUE TITLE
This App Totaly Doesn't Work

### ISSUE THREAD

**Issue by MrDanoni** [malwaredllc/byob#579]
İ generated too much payload (kali linux and standart python payload) and tried another computers but there is no bot. and conections ... I guess payloads doesn't work i couldn't try modules because payloads doesn't work...

**Comment by kittykatgoboom1** [comment]
I would open with something funny and sarcastic but I'm certain it would fly right over your huge smooth brain.

You're totally right though and had the courage to call all of us out. I told the dev and all the boys you were going to figure it out the smoothness of your brain was intimidating. Tens of thousands of us got together with the dev and thought we could trick people into thinking this code worked or even made sense if so many of us pretended like we were loving it and star the repo and stuff.

I guess we will f#ck off now though because it feels weird that you know and this was really weird of us. Thanks bro, im going to make a change today!

**Comment by timotiose** [comment]
> I would open with something funny and sarcastic but I'm certain it would fly right over your huge smooth brain.
> 
> You're totally right though and had the courage to call all of us out. I told the dev and all the boys you were going to figure it out the smoothness of your brain was intimidating. Tens of thousands of us got together with the dev and thought we could trick people into thinking this code worked or even made sense if so many of us pretended like we were loving it and star the repo and stuff.
> 
> I guess we will f#ck off now though because it feels weird that you know and this was really weird of us. Thanks bro, im going to make a change today!

Hes so smoth brain he cant spell or use grammer properly.

**Comment by KoalaV2** [comment]
> > I would open with something funny and sarcastic but I'm certain it would fly right over your huge smooth brain.
> > You're totally right though and had the courage to call all of us out. I told the dev and all the boys you were going to figure it out the smoothness of your brain was intimidating. Tens of thousands of us got together with the dev and thought we could trick people into thinking this code worked or even made sense if so many of us pretended like we were loving it and star the repo and stuff.
> > I guess we will f#ck off now though because it feels weird that you know and this was really weird of us. Thanks bro, im going to make a change today!
> 
> Hes so smoth brain he cant spell or use grammer properly.

*He's, *smooth, *can't, *grammar

sorry i had to lol

**Comment by v1s1t0r999** [comment]
LMAOOO
