### ISSUE TITLE
unable to locate directory containing user-installed packages

### ISSUE THREAD

**Issue by jeremiuwu** [malwaredllc/byob#650]
unable to locate directory containing user-installed packages

when i open it its unable to locate directory containing user-installed packages

**Comment by KMA1707** [comment]
i have got the same problem since weeks

**Comment by Glitch-star496** [comment]
I also have the same problem

**Comment by SHADOW-SCRIPT** [comment]
Same here, just did  sudo pip install flask-bcrypt  in whilst in web-gui, to fix a prob then this happened

**Comment by SHADOW-SCRIPT** [comment]
seems it cant find "create_app"

**Comment by dragonrules** [comment]
anyone found the solution for this yet I am having the same issue

**Comment by dragonrules** [comment]
I managed to get my setup working by following this and running this https://github.com/malwaredllc/byob/issues/587#issuecomment-1236456605

**Comment by SuliiiP** [comment]
> unable to locate directory containing user-installed packages
> 
> when i open it its unable to locate directory containing user-installed packages

First of all, never use sudo pip install. By that, you save yourself a lot of future errors. Use pip install --user instead. Do it right now: got through pip3 list output, try to find packages you already installed (plus their dependencies), uninstall and reinstall them as user. By doing that, you will immediately notice the commands to become available because of the PATH changes you made.
